---
abstract: 'Give access to prctl system call from Perl'
author:
  - 'Troels Liebe Bentsen <troels@infopro.dk>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Prctl
provides:
  Sys::Prctl:
    file: lib/Sys/Prctl.pm
    version: 1.01
requires:
  Config: 0
  POSIX: 0
  perl: '>= 5.8.0'
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
